### ISSUE TITLE
Contribution and Reporting Issues needs to mention your github repo

### ISSUE THREAD

**Issue by mccabete** [ksharonin/feds-benchmarking#13]
You want to revise your Contribution and Reporting to make referese to your repo. Can people submit issues? Also, will you have access to your nasa email moving forward? If no, making your repo the primary means of communication is probably better.

**Comment by ksharonin** [comment]
Just added into the README and JOSS: there is an issues page open to the public and I have also included my berkeley.edu email for a backup
