### ISSUE TITLE
Installing env conflicts | Not reuse basedir

### ISSUE THREAD

**Issue by mccabete** [ksharonin/feds-benchmarking#17]
1) I've tried to make the env from your current repo with conda and mamba in terminal on my laptop (not on maap), and I get a huge list of specifications being incompatible. I would recommend piping the exact env you have wokring on maap into a .yml and updating the .yml you have here (and confirming it is make-able).  OR looking through your package calls and building a new .yml based on the packages you actually use. I'm betting there is a lot of stuff you don't need that's just a dependency of the FEDS  source code. 

2) You re-use the $basedir term for both the [github repo and the env location](https://github.com/ksharonin/feds-benchmarking/blob/FEDS-PEC-Protected/run_dps.sh#L18), which you specifically say not to do earlier in your instructions. It's worth re-working the run-dps.sh, or getting rid of it altogether and provide the lines in the documentation. ie 

`conda env create -f "feds-benchmarking/env-feds.yml" -p "~/env-feds"`

`conda activate env-feds`

**Comment by ksharonin** [comment]
I think it is wiser to just provide the run commands over the shell script, just changed to reflect that
